### PR TITLE
chore: use rustfmt for all rust projects

### PR DESCRIPTION
**Pull request by haraldh**
Makes the code more readable and patching easier.

Fixes: #313

### CODE REVIEW

**Comment by llly** [comment]
Let's only format `QuoteGeneration/quote_wrapper`, `SampleCode/RustSGXQuoteGenerationSample` and `SampleCode/RustTDQuoteGenerationSample`.

**Comment by haraldh** [comment]
Do you want me to modify the PR?

**Comment by llly** [comment]
Yes. Please.

**Comment by haraldh** [comment]
@llly done

**Review by llly — APPROVED** [review]

**Pull request merged**
